---
title: "Upper Walla Walla Watershed - Biological Assessment"
author:
  - Michael W. Ackerman:
      email: mike.ackerman@mthoodenvironmental.com
      institute: [mhe_mccall]
      correspondence: true
  - Tara E. Blackman:
      email: tara.blackman@mthoodenvironmenal.com
      institute: [mhe_sandy]
      correspondence: false
  - Mark Roes:
      email: mark.roes@mthoodenvironmental.com
      institute: [mhe_sandy]
      correspondence: false
  - Kevin E. See:
      email: Kevin.See@dfw.wa.gov
      institute: wdfw
      correspondence: false
institute:
  - mhe_mccall: Mount Hood Environmental, PO Box 4282, McCall, Idaho, 83638, USA
  - mhe_sandy: Mount Hood Environmental, 39085 Pioneer Boulevard \#100 Mezzanine, Sandy, Oregon, 97055, USA
  - wdfw: Washington Department of Fish and Wildife, Fish Program, Science Division, 1111 Washington Street NE, Olympia, Washington, 98501, USA
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  bookdown::html_document2:
    theme: journal
    toc: yes
    toc_depth: 2
    toc_float: yes
    number_sections: yes
    fig_caption: yes
    fig_height: 7
    fig_width: 7
    pandoc_args:
    - --lua-filter=../templates/scholarly-metadata.lua
    - --lua-filter=../templates/author-info-blocks.lua
    - --lua-filter=../templates/pagebreak.lua  
csl: "../templates/american-fisheries-society.csl"
bibliography:
  - AckermanLibrary.bib
---

```{r setup, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  comment = "#>",
  fig.path = "../figures/",
  dpi = 600
)

```

```{r load-libraries}
# run this if running chunks directly

# for analysis
library(sf)
library(here)
library(tidyverse)
library(magrittr)
library(ggmap)
library(nngeo)

```

\newpage

# Introduction
  
      
